apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  labels:
    app: subscription
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscription
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: guycalledjeremy/news_subscription:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: subscription-configmap