apiVersion: v1
kind: Service
metadata:
  name: subscription
spec:
  selector:
    app: subscription
  ports:
    - name: http 
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP