apiVersion: apps/v1
kind: Deployment
metadata:
  name: extraction
  labels:
    app: extraction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extraction
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: extraction
    spec:
      containers:
        - name: extraction
          image: guycalledjeremy/news_extraction:latest
          ports:
            - containerPort: 9050
          envFrom:
            - configMapRef:
                name: extraction-configmap
            - secretRef:
                name: extraction-secret